"""empty message

Revision ID: 1d1b4a63ecbf
Revises: db803f29bebd
Create Date: 2022-03-18 16:35:32.113671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1b4a63ecbf'
down_revision = 'db803f29bebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
